name: Linux (GCC)

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        build-type: [Debug, Release]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Clone repo

    - name: ls1
      run: ls /var/cache/apt/archives/ | wc -l

    - name: Update Archives
      run: sudo apt-get update

    - name: ls2
      run: ls /var/cache/apt/archives/ | wc -l

    - name: Install Cinder Dependencies
      run: >
        sudo apt-get install -y
        libxcursor-dev
        libxrandr-dev
        libxinerama-dev
        libxi-dev
        libgl1-mesa-dev
        libgles2-mesa-dev
        zlib1g-dev
        libfontconfig1-dev
        libsndfile1
        libsndfile1-dev
        libpulse-dev
        libasound2-dev
        libcurl4-gnutls-dev
        libgstreamer1.0-dev
        libgstreamer-plugins-bad1.0-dev
        libgstreamer-plugins-base1.0-dev
        gstreamer1.0-libav
        gstreamer1.0-alsa
        gstreamer1.0-pulseaudio
        gstreamer1.0-plugins-bad
        libboost-filesystem-dev
        libmpg123-dev

    - name: ls3
      run: ls /var/cache/apt/archives/ | wc -l

    - name: Cache Cinder
      id: cache-cinder
      uses: actions/cache@v2
      with:
        path: ~/cache/${{ runner.os }}/Cinder
        key: ${{ runner.os }}-cinder-v0.9.2

    - name: Clone & Build Cinder
      #if: steps.cache-cinder.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/cache/${{ runner.os }}
        cd  ~/cache/${{ runner.os }}
        git clone --recursive --depth 1 --branch v0.9.2 https://github.com/cinder/Cinder.git
        cd Cinder
        cmake -B build -DCMAKE_RELEASE_TYPE=RelWithDebInfo
        cmake --build build

    - name: Generate build files 
      # The -DCMAKE_BUILD_TYPE variable only matters to single-config generators
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

    - name: Build project
      run: cmake --build ${{ github.workspace }}/build

    - name: Run tests
      working-directory: ${{ github.workspace }}/build
      # Run the tests
      run: ctest -C --output-on-failure
