name: MacOS (AppleClang)

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        build-type: [Debug, Release]
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2 # Clone repo

    - name: Cache Cinder
      id: cache-cinder
      uses: actions/cache@v2
      with:
        path: ~/cache/${{ runner.os }}/Cinder
        key: ${{ runner.os }}-cinder-latest

    - name: Clone & Build Cinder
      if: steps.cache-cinder.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/cache/${{ runner.os }}
        cd  ~/cache/${{ runner.os }}
        git clone --recursive --depth 1 https://github.com/cinder/Cinder.git
        cd Cinder
        cd proj/xcode
        ./fullbuild.sh

    - name: Generate build files 
      # The -DCMAKE_BUILD_TYPE variable only matters to single-config generators
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCINDER_PATH=~/cache/${{ runner.os }}/Cinder

    - name: Build project
      run: cmake --build ${{ github.workspace }}/build

    - name: Run tests
      working-directory: ${{ github.workspace }}/build
      # Run the tests
      run: ctest -C --output-on-failure
